import home from "../img/home.svg";
import arrowDown from "../img/chevron-down.svg";
import arrowRight from "../img/chevron-right.svg";
import ecommerce from "../img/circle.svg";
import email from "../img/mail.svg";
import chat from "../img/message-square.svg";
import todo from "../img/check-square.svg";
import calendar from "../img/calendar.svg";
import grid from "../img/layout.svg";
import colors from "../img/droplet.svg";
import card from "../img/credit-card.svg";
import table from "../img/grid.svg";
import components from "../img/archive.svg";
import formElements from "../img/copy.svg";
import formLayouts from "../img/sidebar.svg";
import formWizard from "../img/file-text.svg";
import formValidation from "../img/check-circle.svg";
import favorite from "../img/star.svg";
import notifications from "../img/bell.svg";
import search from "../img/search.svg";
import menu from "../img/list.svg";
import chevronsRight from "../img/chevrons-right.svg";
import settings from "../img/settings.svg";

export const iconHome = home;
export const iconArrowDown = arrowDown;
export const iconArrowRight = arrowRight;
export const iconEcommerce = ecommerce;
export const iconEmail = email;
export const iconChat = chat;
export const iconTodo = todo;
export const iconCalendar = calendar;
export const iconGrid = grid;
export const iconColors = colors;
export const iconCard = card;
export const iconTable = table;
export const iconComponents = components;
export const iconFormElements = formElements;
export const iconFormLayouts = formLayouts;
export const iconFormWizard = formWizard;
export const iconFormValidation = formValidation;
export const iconFavorite = favorite;
export const iconNotifications = notifications;
export const iconSearch = search;
export const iconMenu = menu;
export const iconChevronsRight = chevronsRight;
export const iconSettings = settings;
